<!--BOOK_INFORMATION-->
*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

In [1]:
print("TEST")

TEST


# Reading
Python Programming and Numerical Methods, 
[Chapter 9. Representation of Numbers](https://pythonnumericalmethods.studentorg.berkeley.edu/notebooks/chapter09.00-Representation-of-Numbers.html)

# Problems

## 1. Write a function *my_bin_2_dec(b)*
where *b* is binary number represented by a list of ones and zeros. The last element of *b* represents the coefficient of $2^0$, the second-to-last element of b represents the coefficient of $2^1$, and so on. The output variable, *d*, should be the decimal representation of b. The test cases are provided below. 

In [12]:
def my_bin_2_dec(b):
    n = len(b)
    d = 0
    for i in range(n):
        d+=(b[-n + i]) * (2**(n-1-i))
    return d

In [217]:
# Output: 7
my_bin_2_dec([1, 1, 1])


7

In [5]:
# Output: 85
my_bin_2_dec([1, 0, 1, 0, 1, 0, 1])

85

In [7]:
# Output: 33554431
my_bin_2_dec([1]*25)

33554431

## 2. Write a function *my_dec_2_bin(d)*
where *d* is a positive integer in decimal, and *b* is the binary representation of *d*. The output *b* must be a list of ones and zeros, and the leading term must be a 1 unless the decimal input value is 0. The test cases are provided below. 

In [49]:
import numpy as np
def my_dec_2_bin(d):
    if(d == 0):
        l = 1
    else:
        l = int(np.floor(np.log2(d)) + 1)
    b = np.zeros(l)
    for i in range(l -1, -1, -1):
        r = d % 2
        d = d//2
        b[i] = int(r)
    return b

In [51]:
# Output: [0]
my_dec_2_bin(0)

array([0.])

In [53]:
# Output: [1, 0, 1, 1, 1]
my_dec_2_bin(23)

array([1., 0., 1., 1., 1.])

In [55]:
# Output: [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
my_dec_2_bin(2097)

array([1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.])

## 3. Compute *d = my_bin_2_dec(my_dec_2_bin(12654))*
Use the two functions you wrote in problems 1 and 2. Do you get the same number?

In [58]:
d = my_bin_2_dec(my_dec_2_bin(12654))
print(d)

12654.0


## 4. Write a function *my_bin_adder(b1,b2)*
where *b1*, *b2* and the output variable *b* are binary numbers represented as in problem 1. The output variable should be computed as *b = b1 + b2*. Do not use your functions from problems 1 and 2 to write this function (i.e., do not convert *b1* and *b2* to decimal; add them, and then convert the result back to binary). This function should be able to accept inputs *b1* and *b2* of any length (i.e., very long binary numbers), and *b1* and *b2* may not necessarily be the same length.

In [196]:
def my_bin_adder(b1, b2):
    l1 = len(b1)
    l2 = len(b2)
    if (l1 > l2):
        l = l1 + 1
    elif(l2 > l1):
        l = l2 + 1
    elif(l1 == l2):
        l = l1 + 1
        
    b = np.zeros(l)
    while(len(b1) < l):
        b1 = [0] + b1
    
    while(len(b2) < l):
        b2 = [0] + b2
    
    
    if(b1 == [0] and b2 != [0]):
        b = b2

    elif(b1 != [0] and b2 == [0]):
        b = b1

    elif(b1 == [0] and b2 == [0]):
        b = [0]
    
    elif(b1 != [0] and b2 != [0]):
        i = 0
        while (i < l):
            b[l - (i + 1)] = b1[l - (i + 1)] + b2[l - (i + 1)]
            if ((b1[l - (i + 1)] + b2[l - (i + 1)]) == 2):
                b[l - (i + 1)] = 0
                b1[l - (i + 2)] += 1

            elif((b1[l - (i + 1)] + b2[l - (i + 1)]) == 3):
                b[l - (i + 1)] = 1
                b1[l - (i + 2)] += 1

            elif((b1[l - (i + 1)] + b2[l - (i + 1)]) == 1):
                b[l - (i + 1)] = 1
                
            i += 1

    if(b[0] == 0):
        b = np.delete(b, 0)
        
    
        
    return b

# length = 10
# arr = np.zeros(length)
# print(arr)
# for i in range(length):
#     arr[i] = i
# print(arr)


In [198]:
# Output: [1, 0, 0, 0, 0, 0]
my_bin_adder([1, 0], [1, 1, 1, 1, 1])

array([1., 0., 0., 0., 0., 1.])

In [200]:
# Output: [1, 1, 1, 0, 0, 1, 1]
my_bin_adder([1, 1, 1, 1, 1], [1, 0, 1, 0, 1, 0, 0])

array([1., 1., 1., 0., 0., 1., 1.])

In [202]:
# Output: [1, 0, 1, 1]
my_bin_adder([1, 1, 0], [1, 0, 1])

array([1., 0., 1., 1.])

## 5. What is the effect of allocating more bits to the fraction versus the characteristic and vice versa? What is the effect of allocating more bits to the sign?

I don't know what on earth this question is asking.

## 6. Write a function *my_ieee_2_dec(ieee)*
where *ieee* is a string contains 64 characters of ones and zeros representing a 64-bit IEEE754 number. The output should be *d*, the equivalent decimal representation of *ieee*. The input variable *ieee* will always be a 64-element string of ones and zeros defining a 64-bit float. 

In [10]:
import numpy as np
def my_ieee_2_dec(ieee):
    # 1) convert string to array where the nth element of the array is the nth character in the string
    ieee_Array = list(ieee)
    # 2) if 0th element is 0 or 1 then d is positive (s = 0)
    if ieee_Array[0] == 0 or 1: 
        s = 0
    # 3) if 0th element is - then d is negative (s = 1)
        # make a new array, drop negative sign and shift elements to the left
    if ieee_Array[0] == '-':
        s = 1
        ieee_Array = ieee_Array[1:]
    # 4) extract e from the 1st through 11th elements of the array
    e_Array = ieee_Array[1:11]
    e_string = "".join(e_Array)
    e_bin = int(e_string)
    # 5) extract f from the 12th through Nth element
    N = np.size(ieee_Array)
    f_Array = ieee_Array[12:N]
    f_string = "".join(ieee_Array)
    f_bin = int(f_string)
    # 6) use formula(s, e, f) to convert
    d = ieee_formula(s, e_bin, f_bin)
    return d

def ieee_formula(s, e_bin, f_bin):
    e = my_bin_2_dec(e_bin)
    f = my_bin_2_dec(f_bin)
    return ((-1)**s)*(2**(e-1023))*(1+f)

In [13]:
# Output: -48
ieee = '1100000001001000000000000000000000000000000000000000000000000000'
my_ieee_2_dec(ieee)

TypeError: object of type 'int' has no len()

In [ ]:
# Output: 3.39999999999999991118215802999
ieee = '0100000000001011001100110011001100110011001100110011001100110011'
my_ieee_2_dec(ieee)

## 7. Write a function *my_dec_2_ieee(d)*
where *d* is a number in decimal and output variable *ieee* is a string with 64 characters of ones and zeros representing the 64-bit IEEE754 closest to *d*. You can assume that *d* will not cause an overflow for 64-bit *ieee* numbers.

In [ ]:
def my_dec_2_ieee(d):
    # write your function code here
    
    return ieee

In [ ]:
# Output: '0100000000101110010111101010001110011100001100011010010001101000'

d = 1.518484199625
my_dec_2_ieee(d)

In [ ]:
# Output: '1100000001110011010100100100010010010001001010011000100010010000'

d = -309.141740
my_dec_2_ieee(d)

In [ ]:
# Output: '1100000011011000101010010000000000000000000000000000000000000000'

d = -25252
my_dec_2_ieee(d)

## 8. Define *ieee_baby*
to be a representation of numbers using 6 bits where the first bit is the sign bit, the second and third bits are allocated to the characteristic, and the fourth, fifth, and sixth bits are allocated to the fraction. The normalization for the characteristic is 1.

 - Write all the decimal numbers that can be represented by *ieee_baby*. 
 - What is the largest/smallest gap in *ieee_baby*?

## 9. Use the *np.spacing* function to determine the smallest number such that the gap is 1.

## 10. What are some of the advantages and disadvantages of using binary versus decimal?

## 11. Write the number 13 (base10) in base1. How would you do addition and multiplication in base1?

## 12. How high can you count on your fingers if you count in binary?

## 13. Let *b* be a binary number having *n* digits. Can you think of ways to multiply and divide *b* by 2 that does not involve any arithmetic? Hint: Think about how you multiply and divide a decimal number by 10.